apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-json
  namespace: demo
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  health.json: |
    {
      "service": "backend",
      "status": "ok",
      "message": "hello from backend"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: demo
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: nginx:1.27
          ports:
            - containerPort: 80
          volumeMounts:
            - name: backend-json
              mountPath: /usr/share/nginx/html
      volumes:
        - name: backend-json
          configMap:
            name: backend-json
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: demo
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    app: backend
  ports:
    - port: 80
      targetPort: 80
